#!/usr/bin/env bash
set -e
SCRIPTS_DIR="$(dirname "$0")"
echo "=== August Batch 4: Days 19-24 ==="
echo "--- August 19 ---"
bash "$SCRIPTS_DIR/daily_vault_aug19.sh"
echo ""
echo "--- August 20 ---"
bash "$SCRIPTS_DIR/daily_vault_aug20.sh"
echo ""
echo "--- August 21 ---"
bash "$SCRIPTS_DIR/daily_vault_aug21.sh"
echo ""
echo "--- August 22 ---"
bash "$SCRIPTS_DIR/daily_vault_aug22.sh"
echo ""
echo "--- August 23 ---"
bash "$SCRIPTS_DIR/daily_vault_aug23.sh"
echo ""
echo "--- August 24 ---"
bash "$SCRIPTS_DIR/daily_vault_aug24.sh"
echo ""
echo "Batch 4 complete (6 days)"
