#!/usr/bin/env bash
set -e
SCRIPTS_DIR="$(dirname "$0")"
echo "=== August Batch 3: Days 13-18 ==="
echo "--- August 13 ---"
bash "$SCRIPTS_DIR/daily_vault_aug13.sh"
echo ""
echo "--- August 14 ---"
bash "$SCRIPTS_DIR/daily_vault_aug14.sh"
echo ""
echo "--- August 15 ---"
bash "$SCRIPTS_DIR/daily_vault_aug15.sh"
echo ""
echo "--- August 16 ---"
bash "$SCRIPTS_DIR/daily_vault_aug16.sh"
echo ""
echo "--- August 17 ---"
bash "$SCRIPTS_DIR/daily_vault_aug17.sh"
echo ""
echo "--- August 18 ---"
bash "$SCRIPTS_DIR/daily_vault_aug18.sh"
echo ""
echo "Batch 3 complete (6 days)"
