#!/usr/bin/env bash
set -e
SCRIPTS_DIR="$(dirname "$0")"
echo "=== August Batch 5: Days 25-30 ==="
echo "--- August 25 ---"
bash "$SCRIPTS_DIR/daily_vault_aug25.sh"
echo ""
echo "--- August 26 ---"
bash "$SCRIPTS_DIR/daily_vault_aug26.sh"
echo ""
echo "--- August 27 ---"
bash "$SCRIPTS_DIR/daily_vault_aug27.sh"
echo ""
echo "--- August 28 ---"
bash "$SCRIPTS_DIR/daily_vault_aug28.sh"
echo ""
echo "--- August 29 ---"
bash "$SCRIPTS_DIR/daily_vault_aug29.sh"
echo ""
echo "--- August 30 ---"
bash "$SCRIPTS_DIR/daily_vault_aug30.sh"
echo ""
echo "Batch 5 complete (6 days)"
