#!/usr/bin/env bash
set -e
SCRIPTS_DIR="$(dirname "$0")"
echo "=== August Batch 1: Days 1-6 ==="
echo "--- August 1 ---"
bash "$SCRIPTS_DIR/daily_vault_aug1.sh"
echo ""
echo "--- August 2 ---"
bash "$SCRIPTS_DIR/daily_vault_aug2.sh"
echo ""
echo "--- August 3 ---"
bash "$SCRIPTS_DIR/daily_vault_aug3.sh"
echo ""
echo "--- August 4 ---"
bash "$SCRIPTS_DIR/daily_vault_aug4.sh"
echo ""
echo "--- August 5 ---"
bash "$SCRIPTS_DIR/daily_vault_aug5.sh"
echo ""
echo "--- August 6 ---"
bash "$SCRIPTS_DIR/daily_vault_aug6.sh"
echo ""
echo "Batch 1 complete (6 days)"
