#!/usr/bin/env bash
set -e
SCRIPTS_DIR="$(dirname "$0")"
echo "=== August Batch 2: Days 7-12 ==="
echo "--- August 7 ---"
bash "$SCRIPTS_DIR/daily_vault_aug7.sh"
echo ""
echo "--- August 8 ---"
bash "$SCRIPTS_DIR/daily_vault_aug8.sh"
echo ""
echo "--- August 9 ---"
bash "$SCRIPTS_DIR/daily_vault_aug9.sh"
echo ""
echo "--- August 10 ---"
bash "$SCRIPTS_DIR/daily_vault_aug10.sh"
echo ""
echo "--- August 11 ---"
bash "$SCRIPTS_DIR/daily_vault_aug11.sh"
echo ""
echo "--- August 12 ---"
bash "$SCRIPTS_DIR/daily_vault_aug12.sh"
echo ""
echo "Batch 2 complete (6 days)"
