#!/usr/bin/env bash
set -e
SCRIPTS_DIR="$(dirname "$0")"
echo "━━━ June 16 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun16.sh"
echo ""
echo "━━━ June 17 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun17.sh"
echo ""
echo "━━━ June 18 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun18.sh"
echo ""
echo "━━━ June 19 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun19.sh"
echo ""
echo "━━━ June 20 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun20.sh"
echo ""
echo "━━━ June 21 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun21.sh"
echo ""
echo "━━━ June 22 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun22.sh"
echo ""
echo "━━━ June 23 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun23.sh"
echo ""
echo "━━━ June 24 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun24.sh"
echo ""
echo "━━━ June 25 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun25.sh"
echo ""
echo "━━━ June 26 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun26.sh"
echo ""
echo "━━━ June 27 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun27.sh"
echo ""
echo "━━━ June 28 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun28.sh"
echo ""
echo "━━━ June 29 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun29.sh"
echo ""
echo "━━━ June 30 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jun30.sh"
echo ""
echo "✅ June 16–30 complete"
