#!/usr/bin/env bash
set -e
SCRIPTS_DIR="$(dirname "$0")"
echo "━━━ July 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul1.sh"
echo ""
echo "━━━ July 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul2.sh"
echo ""
echo "━━━ July 3 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul3.sh"
echo ""
echo "━━━ July 4 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul4.sh"
echo ""
echo "━━━ July 5 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul5.sh"
echo ""
echo "━━━ July 6 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul6.sh"
echo ""
echo "━━━ July 7 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul7.sh"
echo ""
echo "━━━ July 8 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul8.sh"
echo ""
echo "━━━ July 9 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul9.sh"
echo ""
echo "━━━ July 10 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul10.sh"
echo ""
echo "━━━ July 11 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul11.sh"
echo ""
echo "━━━ July 12 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul12.sh"
echo ""
echo "━━━ July 13 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul13.sh"
echo ""
echo "━━━ July 14 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul14.sh"
echo ""
echo "━━━ July 15 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul15.sh"
echo ""
echo "━━━ July 16 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul16.sh"
echo ""
echo "━━━ July 17 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul17.sh"
echo ""
echo "━━━ July 18 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul18.sh"
echo ""
echo "━━━ July 19 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul19.sh"
echo ""
echo "━━━ July 20 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul20.sh"
echo ""
echo "━━━ July 21 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul21.sh"
echo ""
echo "━━━ July 22 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul22.sh"
echo ""
echo "━━━ July 23 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul23.sh"
echo ""
echo "━━━ July 24 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul24.sh"
echo ""
echo "━━━ July 25 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul25.sh"
echo ""
echo "━━━ July 26 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul26.sh"
echo ""
echo "━━━ July 27 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul27.sh"
echo ""
echo "━━━ July 28 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul28.sh"
echo ""
echo "━━━ July 29 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul29.sh"
echo ""
echo "━━━ July 30 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul30.sh"
echo ""
echo "━━━ July 31 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_jul31.sh"
echo ""
echo "✅ July 1–31 complete"
