#!/usr/bin/env bash
set -e
SCRIPTS_DIR="$(dirname "$0")"
echo "━━━ August 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug1.sh"
echo ""
echo "━━━ August 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug2.sh"
echo ""
echo "━━━ August 3 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug3.sh"
echo ""
echo "━━━ August 4 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug4.sh"
echo ""
echo "━━━ August 5 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug5.sh"
echo ""
echo "━━━ August 6 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug6.sh"
echo ""
echo "━━━ August 7 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug7.sh"
echo ""
echo "━━━ August 8 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug8.sh"
echo ""
echo "━━━ August 9 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug9.sh"
echo ""
echo "━━━ August 10 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug10.sh"
echo ""
echo "━━━ August 11 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug11.sh"
echo ""
echo "━━━ August 12 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug12.sh"
echo ""
echo "━━━ August 13 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug13.sh"
echo ""
echo "━━━ August 14 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug14.sh"
echo ""
echo "━━━ August 15 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug15.sh"
echo ""
echo "━━━ August 16 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug16.sh"
echo ""
echo "━━━ August 17 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug17.sh"
echo ""
echo "━━━ August 18 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug18.sh"
echo ""
echo "━━━ August 19 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug19.sh"
echo ""
echo "━━━ August 20 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug20.sh"
echo ""
echo "━━━ August 21 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug21.sh"
echo ""
echo "━━━ August 22 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug22.sh"
echo ""
echo "━━━ August 23 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug23.sh"
echo ""
echo "━━━ August 24 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug24.sh"
echo ""
echo "━━━ August 25 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug25.sh"
echo ""
echo "━━━ August 26 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug26.sh"
echo ""
echo "━━━ August 27 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug27.sh"
echo ""
echo "━━━ August 28 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug28.sh"
echo ""
echo "━━━ August 29 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug29.sh"
echo ""
echo "━━━ August 30 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug30.sh"
echo ""
echo "━━━ August 31 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPTS_DIR/daily_vault_aug31.sh"
echo ""
echo "✅ August 1-31 complete"
