name: Package Downloads

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['18', '20', '22']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install package
        run: npm i @greyw0rks/vault-escrow
